# Generated by Django 2.2.10 on 2020-02-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.CharField(default='00-00-0000', max_length=10),
        ),
    ]
