# Generated by Django 2.2.10 on 2020-02-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20200209_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
